# fly.toml app configuration file generated for checkboxer on 2023-06-12T14:06:35+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "checkboxer"
primary_region = "lhr"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
